## 1. Import Necessary Library

In [19]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import keras
from keras.models import Sequential
from keras.layers import Dense

## 2. Daat Collection

In [4]:
diabetes_data = pd.read_csv("diabetes.csv")

In [6]:
diabetes_data

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0              6      148             72             35        0  33.6                     0.627   50        1
1              1       85             66             29        0  26.6                     0.351   31        0
2              8      183             64              0        0  23.3                     0.672   32        1
3              1       89             66             23       94  28.1                     0.167   21        0
4              0      137             40             35      168  43.1                     2.288   33        1
..           ...      ...            ...            ...      ...   ...                       ...  ...      ...
763           10      101             76             48      180  32.9                     0.171   63        0
764            2      122             70             27        0  36.8                     0.340   27        0
765            5      121             72             23      112  26.2                     0.245   30        0
766            1      126             60              0        0  30.1                     0.349   47        1
767            1       93             70             31        0  30.4                     0.315   23        0

[768 rows x 9 columns]

## 3. Data Valiodation

In [7]:
diabetes_data.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [8]:
diabetes_data.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

## 4. Data Preparartion

In [10]:
X = diabetes_data.drop(labels = "Outcome",axis = 1)

In [12]:
y= diabetes_data["Outcome"]

In [15]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size= 0.80,random_state = 12,shuffle= True,stratify=y)

In [16]:
X_train.shape,y_train.shape

((614, 8), (614,))

In [17]:
X_test.shape,y_test.shape

((154, 8), (154,))

### 5. Data PreProcessin (Standadise)

In [20]:
scaller = StandardScaler()

In [21]:
X_train = scaller.fit_transform(X_train)

In [22]:
X_test = scaller.transform(X_test)

In [23]:
X_train.std().round(),X_train.mean().round()

(np.float64(1.0), np.float64(0.0))

In [24]:
X_test.std().round(),X_test.mean().round()

(np.float64(1.0), np.float64(-0.0))

## 6. Module Building

In [25]:
model = Sequential()

In [34]:
model.add(Dense(8,activation = "relu",kernel_initializer='uniform',input_dim=8)) ##Input Layer
model.add(Dense(20,activation= "relu"))
model.add(Dense(10,activation= "relu"))
model.add(Dense(1,activation = "sigmoid"))

C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [35]:
model.compile(optimizer='Adam',loss="BinaryCrossentropy",metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

## 7. Module Training

In [36]:
model.fit(X_train,y_train,batch_size = 40,epochs=30,validation_split = 0.2)

Epoch 1/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 4s 43ms/step - accuracy: 0.5988 - loss: 0.6884 - val_accuracy: 0.6992 - val_loss: 0.6773
Epoch 2/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6395 - loss: 0.6777 - val_accuracy: 0.6992 - val_loss: 0.6611
Epoch 3/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6395 - loss: 0.6683 - val_accuracy: 0.6992 - val_loss: 0.6459
Epoch 4/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6395 - loss: 0.6600 - val_accuracy: 0.6992 - val_loss: 0.6332
Epoch 5/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6395 - loss: 0.6559 - val_accuracy: 0.6992 - val_loss: 0.6271
Epoch 6/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6395 - loss: 0.6546 - val_accuracy: 0.6992 - val_loss: 0.6218
Epoch 7/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6395 - loss: 0.6536 - val_accuracy: 0.6992 - val_loss: 0.6199
Epoch 8/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6395 - loss: 0.6530 - val_accuracy: 0.6992 - val_loss: 0.6193
Epoch 9/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6395 - loss: 0.6530 - val_accuracy: 0.6992 - val_loss: 0.6174
Epoch 10/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6395 - loss: 0.6520 - val_accuracy: 0.6992 - val_loss: 0.6166
Epoch 11/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6395 - loss: 0.6510 - val_accuracy: 0.6992 - val_loss: 0.6175
Epoch 12/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6395 - loss: 0.6500 - val_accuracy: 0.6992 - val_loss: 0.6145
Epoch 13/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6395 - loss: 0.6480 - val_accuracy: 0.6992 - val_loss: 0.6134
Epoch 14/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6395 - loss: 0.6456 - val_accuracy: 0.6992 - val_loss: 0.6112
Epoch 15/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6395 - loss: 0.6422 - val_accuracy: 0.6992 - val_loss: 0.6057
Epoch 16/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6395 - loss: 0.6375 - val_accuracy: 0.6992 - val_loss: 0.6012
Epoch 17/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6395 - loss: 0.6315 - val_accuracy: 0.6992 - val_loss: 0.5986
Epoch 18/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6395 - loss: 0.6234 - val_accuracy: 0.6992 - val_loss: 0.5941
Epoch 19/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6395 - loss: 0.6121 - val_accuracy: 0.6992 - val_loss: 0.5868
Epoch 20/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6395 - loss: 0.5983 - val_accuracy: 0.6992 - val_loss: 0.5784
Epoch 21/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6395 - loss: 0.5808 - val_accuracy: 0.6992 - val_loss: 0.5717
Epoch 22/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6395 - loss: 0.5603 - val_accuracy: 0.6992 - val_loss: 0.5663
Epoch 23/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6395 - loss: 0.5386 - val_accuracy: 0.6992 - val_loss: 0.5638
Epoch 24/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6395 - loss: 0.5195 - val_accuracy: 0.6992 - val_loss: 0.5666
Epoch 25/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7556 - loss: 0.5015 - val_accuracy: 0.6667 - val_loss: 0.5674
Epoch 26/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7800 - loss: 0.4944 - val_accuracy: 0.6748 - val_loss: 0.5774
Epoch 27/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7862 - loss: 0.4882 - val_accuracy: 0.6667 - val_loss: 0.5780
Epoch 28/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7821 - loss: 0.4834 - val_accuracy: 0.6667 - val_loss: 0.5775
Epoch 29/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7862 - loss: 0.4782 - val_accuracy: 0.6992 - val_loss: 0.5889
Epoch 30/30
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7882 - loss: 0.4716 - val_accuracy: 0.6667 - val_loss: 0.5793

In [37]:
from sklearn.metrics import confusion_matrix,accuracy_score

## Module testing

In [39]:
y_Predict = model.predict(X_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

In [45]:
y_Predict = (y_Predict>0.5).astype("int")

In [46]:
y_Predict

array([[0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0]])

## Module Evalution

In [50]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [49]:
print(confusion_matrix(y_test,y_Predict))

[[77 23]
 [15 39]]

In [52]:
print(classification_report(y_test,y_Predict))

              precision    recall  f1-score   support

           0       0.84      0.77      0.80       100
           1       0.63      0.72      0.67        54

    accuracy                           0.75       154
   macro avg       0.73      0.75      0.74       154
weighted avg       0.76      0.75      0.76       154

## test New Data

In [53]:
diabetes_data.head(2)

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72             35        0  33.6                     0.627   50        1
1            1       85             66             29        0  26.6                     0.351   31        0

In [63]:
input_data = np.array([5,120,75,39,0,35,0.725,49])
input_data = input_data.reshape(1,-1)
input_data.shape

(1, 8)

In [57]:
input_data.mean().round(),input_data.std().round()

(np.float64(41.0), np.float64(42.0))

In [64]:
input_data = scaller.transform(input_data)

C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [65]:
input_data.mean().round(),input_data.std().round()

(np.float64(0.0), np.float64(1.0))

In [66]:
predicted_out = model.predict(input_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step

In [68]:
final_Out = (predicted_out>0.5).astype("int")

In [70]:
final_Out,final_Out.shape

(array([[1]]), (1, 1))

In [71]:
print(final_Out[0][0])

1