In [2]:
##pip install mlxtend

## 1. Import library

In [37]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
import warnings
warnings.filterwarnings("ignore")

## 2. Data Collection

In [4]:
Online_Data = pd.read_excel("Online Retail.xlsx")
Online_Data

       InvoiceNo StockCode                          Description  ...  UnitPrice CustomerID         Country
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER  ...       2.55    17850.0  United Kingdom
1         536365     71053                  WHITE METAL LANTERN  ...       3.39    17850.0  United Kingdom
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER  ...       2.75    17850.0  United Kingdom
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE  ...       3.39    17850.0  United Kingdom
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.  ...       3.39    17850.0  United Kingdom
...          ...       ...                                  ...  ...        ...        ...             ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS  ...       0.85    12680.0          France
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL   ...       2.10    12680.0          France
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL   ...       4.15    12680.0          France
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE  ...       4.15    12680.0          France
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT   ...       4.95    12680.0          France

[541909 rows x 8 columns]

In [5]:
Online_Data.describe(include="all")

        InvoiceNo StockCode                         Description  ...      UnitPrice     CustomerID         Country
count    541909.0    541909                              540455  ...  541909.000000  406829.000000          541909
unique    25900.0      4070                                4223  ...            NaN            NaN              38
top      573585.0    85123A  WHITE HANGING HEART T-LIGHT HOLDER  ...            NaN            NaN  United Kingdom
freq       1114.0      2313                                2369  ...            NaN            NaN          495478
mean          NaN       NaN                                 NaN  ...       4.611114   15287.690570             NaN
min           NaN       NaN                                 NaN  ...  -11062.060000   12346.000000             NaN
25%           NaN       NaN                                 NaN  ...       1.250000   13953.000000             NaN
50%           NaN       NaN                                 NaN  ...       2.080000   15152.000000             NaN
75%           NaN       NaN                                 NaN  ...       4.130000   16791.000000             NaN
max           NaN       NaN                                 NaN  ...   38970.000000   18287.000000             NaN
std           NaN       NaN                                 NaN  ...      96.759853    1713.600303             NaN

[11 rows x 8 columns]

In [6]:
Online_Data.nunique()

InvoiceNo      25900
StockCode       4070
Description     4223
Quantity         722
InvoiceDate    23260
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64

In [8]:
Online_Data["Country"].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [9]:
Online_Data.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [19]:
Online_Data["Country"].value_counts()

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [26]:
uk_Online_Data = Online_Data[Online_Data["Country"] == "United Kingdom"]

In [28]:
uk_Online_Data.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [29]:
uk_Online_Data.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     133600
Country             0
dtype: int64

In [31]:
del uk_Online_Data["CustomerID"]

In [32]:
uk_Online_Data

       InvoiceNo StockCode                          Description  ...         InvoiceDate UnitPrice         Country
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER  ... 2010-12-01 08:26:00      2.55  United Kingdom
1         536365     71053                  WHITE METAL LANTERN  ... 2010-12-01 08:26:00      3.39  United Kingdom
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER  ... 2010-12-01 08:26:00      2.75  United Kingdom
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE  ... 2010-12-01 08:26:00      3.39  United Kingdom
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.  ... 2010-12-01 08:26:00      3.39  United Kingdom
...          ...       ...                                  ...  ...                 ...       ...             ...
541889    581585     22466       FAIRY TALE COTTAGE NIGHT LIGHT  ... 2011-12-09 12:31:00      1.95  United Kingdom
541890    581586     22061  LARGE CAKE STAND  HANGING STRAWBERY  ... 2011-12-09 12:49:00      2.95  United Kingdom
541891    581586     23275     SET OF 3 HANGING OWLS OLLIE BEAK  ... 2011-12-09 12:49:00      1.25  United Kingdom
541892    581586     21217        RED RETROSPOT ROUND CAKE TINS  ... 2011-12-09 12:49:00      8.95  United Kingdom
541893    581586     20685                DOORMAT RED RETROSPOT  ... 2011-12-09 12:49:00      7.08  United Kingdom

[495478 rows x 7 columns]

In [33]:
1454/495478

0.002934539979575279

## Data Mining

In [38]:
uk_Online_Data.dropna(inplace = True)

In [39]:
uk_Online_Data.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
Country        0
dtype: int64

In [42]:
uk_pivort_Data = uk_Online_Data.pivot_table(values="Quantity",index="InvoiceNo",columns="Description",aggfunc = "sum").fillna(0)

In [48]:
uk_pivort_Data_onehot = uk_pivort_Data.applymap(lambda x: 0 if x == 0 else 1)

In [49]:
## Online Data One Hotted VAlue Data Frame
uk_pivort_Data_onehot

Description  20713   4 PURPLE FLOCK DINNER CANDLES  ...  wrongly sold as sets  wrongly sold sets
InvoiceNo                                           ...
536365           0                               0  ...                     0                  0
536366           0                               0  ...                     0                  0
536367           0                               0  ...                     0                  0
536368           0                               0  ...                     0                  0
536369           0                               0  ...                     0                  0
...            ...                             ...  ...                   ...                ...
C581484          0                               0  ...                     0                  0
C581490          0                               0  ...                     0                  0
C581499          0                               0  ...                     0                  0
C581568          0                               0  ...                     0                  0
C581569          0                               0  ...                     0                  0

[22040 rows x 4202 columns]

## ML Exdent Association

In [54]:
apprior_DF = apriori(df = uk_pivort_Data_onehot ,min_support=0.02,use_colnames = True)

In [56]:
best_Associates = association_rules(df = apprior_DF,min_threshold = 0.2)

In [58]:
best_Associates

                                          antecedents  ... kulczynski
0                         (ALARM CLOCK BAKELIKE RED )  ...   0.614896
1                        (ALARM CLOCK BAKELIKE GREEN)  ...   0.614896
2                       (RED RETROSPOT CHARLOTTE BAG)  ...   0.612279
3                       (CHARLOTTE BAG PINK POLKADOT)  ...   0.612279
4                       (RED RETROSPOT CHARLOTTE BAG)  ...   0.553677
..                                                ...  ...        ...
85  (GREEN REGENCY TEACUP AND SAUCER, ROSES REGENC...  ...   0.687083
86  (PINK REGENCY TEACUP AND SAUCER, ROSES REGENCY...  ...   0.702326
87                  (GREEN REGENCY TEACUP AND SAUCER)  ...   0.702326
88                   (PINK REGENCY TEACUP AND SAUCER)  ...   0.687083
89                 (ROSES REGENCY TEACUP AND SAUCER )  ...   0.672543

[90 rows x 14 columns]

## Export to CSV

In [57]:
best_Associates.to_csv("Best_Association_List.csv")