## 1. Import Necessary Library

In [78]:
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.datasets import boston_housing
from sklearn.preprocessing import StandardScaler
import pandas as pd

## 2. Data Collection

In [79]:
(X_train, y_train), (X_test, y_test) = boston_housing.load_data()

In [80]:
X_train.shape,y_train.shape

((404, 13), (404,))

In [81]:
X_test.shape,y_test.shape

((102, 13), (102,))

## 3. Data Preparation

In [10]:
## Stadarditation

In [83]:
scaller = StandardScaler()

In [84]:
X_train_scall = scaller.fit_transform(X_train)
X_test_scall = scaller.fit_transform(X_test)

In [85]:
X_train_scall.mean().round(),X_train_scall.std().round()

(np.float64(0.0), np.float64(1.0))

In [18]:
pd.DataFrame(X_train_scall)

           0         1         2         3         4   ...        8         9         10        11        12
0   -0.272246 -0.483615 -0.435762 -0.256833 -0.165227  ... -0.626249 -0.595170  1.148500  0.448077  0.825220
1   -0.403427  2.991784 -1.333912 -0.256833 -1.215182  ... -0.856463 -0.348433 -1.718189  0.431906 -1.329202
2    0.124940 -0.483615  1.028326 -0.256833  0.628642  ...  1.675886  1.565287  0.784476  0.220617 -1.308500
3   -0.401494 -0.483615 -0.869402 -0.256833 -0.361560  ... -0.511142 -1.094663  0.784476  0.448077 -0.652926
4   -0.005634 -0.483615  1.028326 -0.256833  1.328612  ...  1.675886  1.565287  0.784476  0.389882  0.263497
..        ...       ...       ...       ...       ...  ...       ...       ...       ...       ...       ...
399 -0.381973 -0.483615 -0.616568 -0.256833 -0.933487  ... -0.741356 -1.040501 -0.262093  0.448077  0.477421
400 -0.388221  0.358906 -0.609218 -0.256833 -0.796907  ... -0.741356 -1.100681  0.056428  0.448077 -0.848908
401 -0.402030  0.990797 -0.741515 -0.256833 -1.019702  ... -0.971569 -0.613224 -0.717123  0.079439 -0.677769
402 -0.172920 -0.483615  1.245881 -0.256833  2.677335  ... -0.511142 -0.017443 -1.718189 -0.987644  0.420835
403 -0.404226  2.043948 -1.201615 -0.256833 -1.334689  ... -0.971569 -0.847926 -1.308662  0.233171 -1.153923

[404 rows x 13 columns]

In [86]:
pd.DataFrame(X_train)

          0     1      2    3       4      5      6       7     8      9     10      11     12
0    1.23247   0.0   8.14  0.0  0.5380  6.142   91.7  3.9769   4.0  307.0  21.0  396.90  18.72
1    0.02177  82.5   2.03  0.0  0.4150  7.610   15.7  6.2700   2.0  348.0  14.7  395.38   3.11
2    4.89822   0.0  18.10  0.0  0.6310  4.970  100.0  1.3325  24.0  666.0  20.2  375.52   3.26
3    0.03961   0.0   5.19  0.0  0.5150  6.037   34.5  5.9853   5.0  224.0  20.2  396.90   8.01
4    3.69311   0.0  18.10  0.0  0.7130  6.376   88.4  2.5671  24.0  666.0  20.2  391.43  14.65
..       ...   ...    ...  ...     ...    ...    ...     ...   ...    ...   ...     ...    ...
399  0.21977   0.0   6.91  0.0  0.4480  5.602   62.0  6.0877   3.0  233.0  17.9  396.90  16.20
400  0.16211  20.0   6.96  0.0  0.4640  6.240   16.3  4.4290   3.0  223.0  18.6  396.90   6.59
401  0.03466  35.0   6.06  0.0  0.4379  6.031   23.3  6.6407   1.0  304.0  16.9  362.25   7.83
402  2.14918   0.0  19.58  0.0  0.8710  5.709   98.5  1.6232   5.0  403.0  14.7  261.95  15.79
403  0.01439  60.0   2.93  0.0  0.4010  6.604   18.8  6.2196   1.0  265.0  15.6  376.70   4.38

[404 rows x 13 columns]

## 4. Module Building

In [87]:
bos_module = Sequential()

In [88]:
bos_module.add(Dense( units = 64,activation="relu",input_shape = (13,))) ##Input Layer
bos_module.add(Dense(32,activation= "relu"))
bos_module.add(Dense(10,activation= "relu"))
bos_module.add(Dense(1)) ## OuptLayer

C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [89]:
bos_module.compile(optimizer='adam',loss="mse",metrics = ["mae"])

## 5. Module Training | Module Test | Module Evaluation

In [90]:
bos_module.fit(x=X_train_scall,
    y=y_train,
    batch_size=20,
    epochs=100,
    verbose=1,
    validation_split = 0.2)

Epoch 1/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 563.2192 - mae: 21.8713 - val_loss: 614.9387 - val_mae: 23.0446
Epoch 2/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 522.0799 - mae: 20.9263 - val_loss: 556.8801 - val_mae: 21.7741
Epoch 3/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 454.2827 - mae: 19.2956 - val_loss: 461.8323 - val_mae: 19.5443
Epoch 4/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 347.4893 - mae: 16.4523 - val_loss: 319.6384 - val_mae: 15.7110
Epoch 5/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 210.4834 - mae: 12.2802 - val_loss: 165.4738 - val_mae: 10.1659
Epoch 6/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 104.4448 - mae: 8.0443 - val_loss: 92.4681 - val_mae: 7.2408
Epoch 7/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 69.3467 - mae: 6.4222 - val_loss: 67.4618 - val_mae: 6.1831
Epoch 8/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 50.5041 - mae: 5.3578 - val_loss: 48.2641 - val_mae: 5.1030
Epoch 9/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 37.5556 - mae: 4.5059 - val_loss: 36.9270 - val_mae: 4.3839
Epoch 10/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 30.4972 - mae: 3.9518 - val_loss: 30.8532 - val_mae: 4.0160
Epoch 11/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 26.6802 - mae: 3.6156 - val_loss: 26.7941 - val_mae: 3.7548
Epoch 12/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.8732 - mae: 3.4290 - val_loss: 23.8700 - val_mae: 3.5942
Epoch 13/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 21.7920 - mae: 3.3456 - val_loss: 22.1669 - val_mae: 3.5469
Epoch 14/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.6587 - mae: 3.2293 - val_loss: 20.9903 - val_mae: 3.3819
Epoch 15/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 19.2074 - mae: 3.0574 - val_loss: 20.1180 - val_mae: 3.3272
Epoch 16/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 18.3446 - mae: 2.9805 - val_loss: 19.2998 - val_mae: 3.2567
Epoch 17/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 17.5634 - mae: 2.9439 - val_loss: 18.4143 - val_mae: 3.1940
Epoch 18/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 16.8396 - mae: 2.8911 - val_loss: 17.8376 - val_mae: 3.1343
Epoch 19/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 16.0829 - mae: 2.7788 - val_loss: 17.1822 - val_mae: 3.0657
Epoch 20/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 15.6865 - mae: 2.7814 - val_loss: 16.8062 - val_mae: 3.0540
Epoch 21/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 15.3594 - mae: 2.6600 - val_loss: 16.2565 - val_mae: 3.0094
Epoch 22/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 14.3705 - mae: 2.6116 - val_loss: 15.8217 - val_mae: 2.9783
Epoch 23/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.8968 - mae: 2.6522 - val_loss: 15.3552 - val_mae: 2.9094
Epoch 24/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.4483 - mae: 2.5903 - val_loss: 15.0134 - val_mae: 2.9088
Epoch 25/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.0626 - mae: 2.4851 - val_loss: 14.5629 - val_mae: 2.8797
Epoch 26/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12.4746 - mae: 2.4541 - val_loss: 14.2171 - val_mae: 2.8168
Epoch 27/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.2818 - mae: 2.4788 - val_loss: 14.0056 - val_mae: 2.7989
Epoch 28/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.9817 - mae: 2.3928 - val_loss: 13.6931 - val_mae: 2.7873
Epoch 29/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.6351 - mae: 2.3730 - val_loss: 14.0675 - val_mae: 2.7982
Epoch 30/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.5678 - mae: 2.3663 - val_loss: 13.3022 - val_mae: 2.7253
Epoch 31/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.1342 - mae: 2.3100 - val_loss: 13.4569 - val_mae: 2.7517
Epoch 32/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.8228 - mae: 2.2913 - val_loss: 13.3494 - val_mae: 2.7072
Epoch 33/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.7880 - mae: 2.3644 - val_loss: 13.6131 - val_mae: 2.7200
Epoch 34/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.6858 - mae: 2.2644 - val_loss: 13.2852 - val_mae: 2.7461
Epoch 35/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.6778 - mae: 2.3076 - val_loss: 13.5707 - val_mae: 2.7046
Epoch 36/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.0307 - mae: 2.1996 - val_loss: 13.0686 - val_mae: 2.7327
Epoch 37/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.9671 - mae: 2.1659 - val_loss: 12.8580 - val_mae: 2.6666
Epoch 38/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 9.6753 - mae: 2.1679 - val_loss: 12.8366 - val_mae: 2.6343
Epoch 39/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.7412 - mae: 2.1565 - val_loss: 13.2012 - val_mae: 2.6544
Epoch 40/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.5842 - mae: 2.1887 - val_loss: 13.2453 - val_mae: 2.5894
Epoch 41/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.2756 - mae: 2.3448 - val_loss: 13.4813 - val_mae: 2.5871
Epoch 42/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.4438 - mae: 2.1599 - val_loss: 12.9540 - val_mae: 2.6955
Epoch 43/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.3569 - mae: 2.1520 - val_loss: 12.9158 - val_mae: 2.6315
Epoch 44/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.0413 - mae: 2.1196 - val_loss: 13.0436 - val_mae: 2.5882
Epoch 45/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7886 - mae: 2.0934 - val_loss: 12.8492 - val_mae: 2.6543
Epoch 46/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7788 - mae: 2.0843 - val_loss: 12.7736 - val_mae: 2.6308
Epoch 47/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7509 - mae: 2.0309 - val_loss: 12.8070 - val_mae: 2.6356
Epoch 48/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7336 - mae: 2.0827 - val_loss: 13.0430 - val_mae: 2.5691
Epoch 49/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.8262 - mae: 2.0565 - val_loss: 13.1786 - val_mae: 2.6441
Epoch 50/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.3726 - mae: 2.0379 - val_loss: 13.2530 - val_mae: 2.5776
Epoch 51/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.3135 - mae: 2.0165 - val_loss: 13.0287 - val_mae: 2.5409
Epoch 52/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.1634 - mae: 2.0011 - val_loss: 12.9725 - val_mae: 2.5456
Epoch 53/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.1901 - mae: 1.9805 - val_loss: 13.0759 - val_mae: 2.5495
Epoch 54/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2345 - mae: 2.0220 - val_loss: 13.2876 - val_mae: 2.5921
Epoch 55/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.9959 - mae: 1.9766 - val_loss: 13.3696 - val_mae: 2.5693
Epoch 56/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9269 - mae: 1.9889 - val_loss: 13.3824 - val_mae: 2.5497
Epoch 57/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0479 - mae: 1.9604 - val_loss: 13.2910 - val_mae: 2.5699
Epoch 58/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.1467 - mae: 2.0335 - val_loss: 13.5573 - val_mae: 2.5335
Epoch 59/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.6911 - mae: 1.9212 - val_loss: 13.2331 - val_mae: 2.5749
Epoch 60/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7586 - mae: 1.9387 - val_loss: 13.7219 - val_mae: 2.5485
Epoch 61/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 7.6636 - mae: 1.9581 - val_loss: 13.6625 - val_mae: 2.5372
Epoch 62/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.7166 - mae: 1.9141 - val_loss: 13.2395 - val_mae: 2.5190
Epoch 63/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.0741 - mae: 2.1898 - val_loss: 14.4487 - val_mae: 2.5407
Epoch 64/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6573 - mae: 1.9670 - val_loss: 13.9026 - val_mae: 2.6708
Epoch 65/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.5720 - mae: 1.9216 - val_loss: 14.1226 - val_mae: 2.6183
Epoch 66/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.3598 - mae: 1.8997 - val_loss: 13.8182 - val_mae: 2.5764
Epoch 67/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.1927 - mae: 1.8811 - val_loss: 13.7813 - val_mae: 2.5353
Epoch 68/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.3427 - mae: 1.8898 - val_loss: 14.2725 - val_mae: 2.5819
Epoch 69/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.0704 - mae: 1.8667 - val_loss: 13.6695 - val_mae: 2.5352
Epoch 70/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.0603 - mae: 1.8617 - val_loss: 14.0983 - val_mae: 2.5778
Epoch 71/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.3405 - mae: 1.9108 - val_loss: 13.4984 - val_mae: 2.5045
Epoch 72/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.0349 - mae: 1.8318 - val_loss: 13.7378 - val_mae: 2.5690
Epoch 73/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.9124 - mae: 1.8628 - val_loss: 14.3894 - val_mae: 2.5041
Epoch 74/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9273 - mae: 1.8548 - val_loss: 13.9705 - val_mae: 2.5549
Epoch 75/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.8494 - mae: 1.8170 - val_loss: 13.7966 - val_mae: 2.5192
Epoch 76/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.9554 - mae: 1.8598 - val_loss: 14.5864 - val_mae: 2.5776
Epoch 77/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.8264 - mae: 1.8368 - val_loss: 13.9604 - val_mae: 2.5778
Epoch 78/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.6544 - mae: 1.8053 - val_loss: 14.4401 - val_mae: 2.5209
Epoch 79/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.7474 - mae: 1.8068 - val_loss: 13.7559 - val_mae: 2.5154
Epoch 80/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.6242 - mae: 1.7994 - val_loss: 13.8981 - val_mae: 2.5199
Epoch 81/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.5477 - mae: 1.7985 - val_loss: 14.1571 - val_mae: 2.5190
Epoch 82/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.6347 - mae: 1.7731 - val_loss: 14.2179 - val_mae: 2.5164
Epoch 83/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4812 - mae: 1.7917 - val_loss: 14.6362 - val_mae: 2.5359
Epoch 84/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.5754 - mae: 1.7742 - val_loss: 14.5803 - val_mae: 2.5171
Epoch 85/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.3854 - mae: 1.7805 - val_loss: 14.3210 - val_mae: 2.5185
Epoch 86/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.4394 - mae: 1.7795 - val_loss: 13.7375 - val_mae: 2.5435
Epoch 87/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.2921 - mae: 1.7390 - val_loss: 14.0532 - val_mae: 2.5195
Epoch 88/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.2284 - mae: 1.7423 - val_loss: 14.2769 - val_mae: 2.5105
Epoch 89/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2359 - mae: 1.7163 - val_loss: 14.0766 - val_mae: 2.5008
Epoch 90/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.1830 - mae: 1.7306 - val_loss: 13.9374 - val_mae: 2.5168
Epoch 91/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2247 - mae: 1.7278 - val_loss: 14.1672 - val_mae: 2.5138
Epoch 92/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.1018 - mae: 1.6947 - val_loss: 14.1310 - val_mae: 2.5045
Epoch 93/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.9956 - mae: 1.7041 - val_loss: 13.8972 - val_mae: 2.4799
Epoch 94/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.3432 - mae: 1.7543 - val_loss: 14.1111 - val_mae: 2.5024
Epoch 95/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.0987 - mae: 1.7191 - val_loss: 14.2965 - val_mae: 2.5051
Epoch 96/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.0289 - mae: 1.6871 - val_loss: 14.4278 - val_mae: 2.4895
Epoch 97/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.2158 - mae: 1.7833 - val_loss: 14.0043 - val_mae: 2.5476
Epoch 98/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2429 - mae: 1.7255 - val_loss: 14.4263 - val_mae: 2.4429
Epoch 99/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8298 - mae: 1.6686 - val_loss: 14.2894 - val_mae: 2.5415
Epoch 100/100
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.0241 - mae: 1.7374 - val_loss: 13.9296 - val_mae: 2.4712

In [91]:
bos_module.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 64)                  │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 10)                  │             330 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 1)                   │              11 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9,953 (38.88 KB)

 Trainable params: 3,317 (12.96 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 6,636 (25.93 KB)

## Module Evaluation

In [92]:
loss,mae = bos_module.evaluate(X_test_scall,y_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 18.7844 - mae: 2.8661

In [93]:
loss,mae

(18.784378051757812, 2.8660666942596436)

## Model Prediction

In [94]:
# Example new data (13 features)
new_data = np.array([[0.02, 18, 2.5, 0, 0.45, 6.5, 65, 4.5, 1, 300, 15, 390, 5]])

# Apply same scaling
new_data = scaller.transform(new_data)

# Predict
prediction = bos_module.predict(new_data)

print("Predicted House Price:", prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step
Predicted House Price: [[28.60868]]

## Deployement

In [95]:
from pickle import dump,load

In [96]:
dump(obj = scaller,file = open("scaller.pkl",mode = "wb"))

In [97]:
Input_Scaller = load(file = open("scaller.pkl",mode = "rb"))

In [98]:
new_data = np.array([[0.02, 18, 2.5, 0, 0.45, 6.5, 65, 4.5, 1, 300, 15, 390, 5]])
new_data.mean().round(),new_data.std().round()

(np.float64(62.0), np.float64(123.0))

In [76]:
new_data = scaller.fit_transform(new_data)

In [99]:
new_data = Input_Scaller.transform(new_data)

In [100]:
new_data.mean().round(),new_data.std().round()

(np.float64(-0.0), np.float64(1.0))

In [101]:
prediction = bos_module.predict(new_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step

In [102]:
print(prediction)

[[28.60868]]